Feature ETP-10: New Test Pipeline
etendosoftware/com.etendorx.gradlepluginrx pull request #10
Opened 2024-08-19 12:24 UTC by LucasAguirre99

A pipeline was created to be able to perform the gradlew tests, and a report is also saved within the same Jenkins environment

2024-08-19 14:42 UTC, valeg-etendo requested changes

2024-08-19 14:45 UTC, valeg-etendo requested changes

2024-08-19 14:45 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +              error("Tests failed: ${e.message}")
```suggestion
              unstable("Tests failed: ${e.message}")
```

2024-08-22 12:11 UTC, valeg-etendo requested changes

2024-08-23 12:37 UTC, valeg-etendo approved these changes

2024-08-23 12:37 UTC, valeg-etendo commented on pipelines/Jenkinsfile
> +            <p>The 'App Loader' tests have failed.<br>Check out the output in the following link: ${env.BUILD_URL}
```suggestion
            <p>The '${REPO_NAME}' tests have failed.<br>Check out the output in the following link: ${env.BUILD_URL}
```

2024-08-26 17:16 UTC, valenvivaldi approved these changes

2024-08-26 17:23 UTC, merged